### ISSUE TITLE
Analyze UI-Freezes in Grafana dashboard and extract issues out of them

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-Platform#119]
# Goal
Regularly check this dashboard and extract some issues out of it: [UI Freezes (Grafana)](https://dash.dev.monitor.ppt.vi.vector.int/d/ZG8_wtUGk/ui-freezes?orgId=1&from=now-30d&to=now)

# Hints
* Always check that the stack trace is **up-to-date** _i.e._ check that the line numbers actually reflect the current stack trace. The reason for this is that we (PPT) are always some months behind schedule and use an "old" Eclipse which means that the UI-Freezes may have already been fixed in newer versions of Eclipse.
* Some issues are irrelevant since they occur in 3rd-party plugins _e.g._ in **Subversion's SVN client**. See (and expand) the section _Current Issues > Ignore_ below.
* Try to find the issues that happen more often (column "Count") and/or freeze the UI for the longest periods of time (column "Median duration").
* Play with the interval of time (it's on the top-right corner). I usually go for **Last 30 days**
* You can export the data as a CSV and work with it in Excel.

# Expected results
* Issues should be created and added to this board.
* The issues should be linked to this issue too in order to better keep track of them.

# Current issues
This is a first prioritization, feel free to pick one and create an issue for it:

## Prioritized (the higher in the list, the more important)
1. `at org.eclipse.jdt.internal.core.JavaModelManager.determineIfOnClasspath(JavaModelManager.java:1207)`
2. `at org.eclipse.core.internal.watson.ElementTree.includes(ElementTree.java:549)`
3. `at org.eclipse.jdt.internal.core.JavaModelManager.getInfo(JavaModelManager.java:2268)`
4. `at org.eclipse.core.internal.dtree.AbstractDataTreeNode.indexOfChild(AbstractDataTreeNode.java:463)`
5. `at org.eclipse.ui.internal.views.markers.Markers.getMarkerCounts(Markers.java:311)`

## Not prioritized
- `at org.eclipse.jface.text.source.AnnotationModel$RegionIterator.findNext(AnnotationModel.java:114)`
- `at org.eclipse.pde.internal.core.PluginModelManager.isInitialized(PluginModelManager.java:493)`
- `at org.eclipse.jdt.internal.core.JavaElement.getAncestor(JavaElement.java:240)`
- `at org.eclipse.jdt.internal.ui.javaeditor.ClipboardOperationAction.doCutCopyWithImportsOperation(ClipboardOperationAction.java:404)`

## Ignore
- `at org.eclipse.swt.internal.ole.win32.COM.VtblCall(Native Method)`
- `at org.eclipse.swt.internal.win32.OS.ScriptShape(Native Method)`
- `at org.tigris.subversion.subclipse.core.resources.ResourceStatus$StatusFromBytesStream.readString(ResourceStatus.java:667)`

**Comment by fedejeanne** [comment]
@christianstaib I moved the issue here so we can all see the same issues and avoid duplicate work. I'll remove the "original" issue in the other backlog.

**Comment by christianstaib** [comment]
Prioritized item 2 (at org.eclipse.core.internal.watson.ElementTree.includes(ElementTree.java:549)) might be related to opening a Problems view the first time after startup with many problems. In the meantime I was able to reproduce the freeze at least one time but im still not quit sure what conditions have to be meet to trigger the freeze.

**Comment by fedejeanne** [comment]
@christianstaib  👍 . Please post the steps you followed and I'll give it a try. If I can't reproduce the freeze after a few attempts then we may move to another issue.
