### ISSUE TITLE
SWT exception when opening XML file

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-Platform#158]
This exception is thrown when opening an XML file with the XML editor from [eclipse-sourceediting](https://github.com/eclipse-sourceediting/sourceediting):

```java
 java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4903)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:428)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:262)
	at org.eclipse.swt.graphics.Image.applyDisableImageData(Image.java:634)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:274)
	at org.eclipse.jface.resource.DerivedImageDescriptor.internalCreateImage(DerivedImageDescriptor.java:83)
	at org.eclipse.jface.resource.DerivedImageDescriptor.createResource(DerivedImageDescriptor.java:51)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:56)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
	at org.eclipse.jface.resource.LazyResourceManager.create(LazyResourceManager.java:88)
	at org.eclipse.jface.resource.LocalResourceManager.allocate(LocalResourceManager.java:71)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
	at org.eclipse.jface.resource.ResourceManager.createImageWithDefault(ResourceManager.java:192)
	at org.eclipse.jface.action.ActionContributionItem.updateImages(ActionContributionItem.java:1017)
	at org.eclipse.jface.action.ActionContributionItem.updateToolItem(ActionContributionItem.java:777)
	at org.eclipse.jface.action.ActionContributionItem.update(ActionContributionItem.java:740)
	at org.eclipse.jface.action.ActionContributionItem.fill(ActionContributionItem.java:351)
	at org.eclipse.jface.action.ToolBarManager.update(ToolBarManager.java:358)
	at org.eclipse.wst.xml.ui.internal.tabletree.XMLMultiPageEditorPart.addEditorActions(XMLMultiPageEditorPart.java:759)
	at org.eclipse.wst.xml.ui.internal.tabletree.XMLMultiPageEditorPart.createDesignPage(XMLMultiPageEditorPart.java:668)
	at org.eclipse.wst.xml.ui.internal.tabletree.XMLMultiPageEditorPart.createAndAddDesignPage(XMLMultiPageEditorPart.java:643)
	at org.eclipse.wst.xml.ui.internal.tabletree.XMLMultiPageEditorPart.createPages(XMLMultiPageEditorPart.java:774)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:381)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
...
```

Permalink: [XMLMultiPageEditorPart.java:759](https://github.com/eclipse-sourceediting/sourceediting/blob/bdf63c0f061b10059ffcec9350ec8da210b512f4/xml/bundles/org.eclipse.wst.xml.ui/src-multipage/org/eclipse/wst/xml/ui/internal/tabletree/XMLMultiPageEditorPart.java#L759).

**Comment by fedejeanne** [comment]
@akoch-yatta I'm passing it to you since I'm working on the failed builds.

I was focusing on creating a reproducer (ideally even a test) but I couldn't do it. I will add the setup I used to the description of this Issue so you can easily test things manually.

**Comment by akoch-yatta** [comment]
For testing, you can directly add the dependency in the Platform SDK and debug directly out of the runtime

![image](https://github.com/user-attachments/assets/e8dc3187-6a51-468a-91ba-448394e6a989)
