### ISSUE TITLE
Ensure Thread-Safety of SWTFontProvider Implementations

### ISSUE THREAD

**Issue by HeikoKlare** [vi-eclipse/Eclipse-Platform#98]
Since the Windows SWT implementations allows to have multiple `Display` instances, the `SWTFontRegistry` implementations might be accessed concurrently from multiple `Display` instances. It should be checked whether the implementation are already or need to be thread-safe, or their thread-safety shall be ensured and tested.

**Comment by fedejeanne** [comment]
@HeikoKlare / @akoch-yatta I'm done with the analysis but I would like to go over the results with you before I close the issue.

We can do it in a call or just by commenting on this issue. 

Let me know if I should organize a call.

**Comment by HeikoKlare** [comment]
Thank you for the analysis! I think there are some findings in there, which we need to discuss.

Before coming to the different findings, one general statement on this issue: the first question to answer here is whether `SWTFontRegistry` _needs to be_ thread-safe at all. Since it is an internal class that no one outside is supposed to use (and it does not guarantee thread-safety in particular), we must have a look at its usages. I have taken a look at callers of the methods and, if I am not mistaken, all of them need to be executed from the according display's UI thread. So all of them that do not modify the internal data structure (the map of devices to regstries) _are not_ thread-safe (due to missing happens-before relations of method calls across threads) but they do _not need to be_ either, as they cannot be called from different threads.
What remains are `getFontRegistry()` and `disposeFontRegistry()`, which change the internal data structure and thus may require proper synchronization across threads.
So here are my comments on the points regarding them:

1.  `org.eclipse.swt.internal.SWTFontProvider.getFontRegistry(Device)` uses `java.util.Map.computeIfAbsent(...)` 
    - This is the only critical point (regarding thread-safety) that I see. There is no happens-before relation between accesses to the map in different threads, thus they may see different states of the map. This is not necessarily a problem, as each thread is only interested in whether a registry is already there for _its_ device (not for any other), to whose eventual previous addition there _is_ a happens-before relation (as it happened in the same thread). So probably this is not even an issue. In other words: the font registry here could potentially also be realized as a thread-local variable.
    - Still, I am not sure how the HashMap implementation works internally, so it might happen that a thread overwrites values already written by the other (e.g., in case of a hash conflict of two devices), which then eventually (upon synchronization between data seen by the threads like a cache flush) leads to concurrency issues. So it would probably be wise to have a thorough look here.
    - We usually only do a retrieval and very seldom add an element (only when a new device is created). So it might be better (from performance perspective) to synchronize the addition to the map in case the element is missing instead of synchronizing every access (via a ConcurrentHashMap).
2. `org.eclipse.swt.internal.SWTFontProvider.fontRegistries` (a `Map<Device, SWTFontRegistry>`) uses `Device` as a key. 
   - This is a valid point (though not related to thread-safety but to regression-safety). I consider the risk as rather low as I think one would be afraid of people already relying on hashCode and equals behaving like they always did for Device/Display, but still nothing we can be safe of.
   - I am not sure whether we should address this. Anyway, just using `Object.hash(device)` would not solve the issue as that method uses `device.hashCode()` internally, thus it is also not safe against changes to the hashCode implementation of Device.
3. `org.eclipse.swt.internal.ScalingSWTFontRegistry.fontKeyMap` uses `FontData` as key
   - I also think this is a valid point and, like the previous, it is not thread-safety-related. But it is actually something that could also occur right now within the code. I don't think it is intended to modify font data, but of course someone could do it.
   - It seems rather dangerous to use the same font data inside the registry that is also passed (as a mutable object) outside of it. But since I have the impression that font data is shared quite often, modifying them would usually lead to problems soon, wouldn't it? @akoch-yatta do you have seen anything like this so far?
4. `org.eclipse.swt.internal.SWTFontProvider.disposeFontRegistry(Device)` uses `java.util.Map.remove(Object)`
   -  Same as (1) and should be solved together.

**Comment by fedejeanne** [comment]
> the first question to answer here is whether `SWTFontRegistry` _needs to be_ thread-safe at all

I'm with you on this and I also kept that in mind while doing the analysis. I also think that there is not a big risk of race conditions in practice because the thread departamentation in SWT is doing most of the safekeeping already, as you mentioned. 
Regarding performance, the official [JavaDoc of `ConcurrentHashMap`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/ConcurrentHashMap.html) says that:

> [...]  However, even though all operations are thread-safe, retrieval operations do not entail locking [...]

This means that in our scenario where we have more reads than writes, the performance should be fine. When the time comes, if we're still deciding of whether or not we _need_ to make it thread-safe or if we just leave that to the callers, we could just give it a try and see if performance suffers in order to make a better decision.

> 2. [...] Anyway, just using `Object.hash(device)` would not solve the issue as that method uses `device.hashCode()` internally [...}

You're right, I actually even checked this but forgot to change the text. I meant [`System.identityHashCode(Object)`](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#identityHashCode-java.lang.Object-). I corrected the text, thank you for checking it!

> 3. [...] It seems rather dangerous to use the same font data inside the registry that is also passed (as a mutable object) outside of it. But since I have the impression that font data is shared quite often, modifying them would usually lead to problems soon, wouldn't it?

Agreed. Even more: the other side of the coin here is that if we "fix" this issue (say by using `System.identityHashCode(fontData)` as the key in the map) and then someone simply expects to find something in the map by using a newly created `FontData fdCopy` such that `fdOriginal.hashCode() == fdCopy.hashCode() && fd.Original.equals(fdCopy)` then indexing with the _system_ hash code wouldn't work. What I'm saying here is: the expected behavior of the map depends on the caller.

**Comment by HeikoKlare** [comment]
Can we please make issues out of the findings and prioritize them? The actual, currently existing issues w.r.t. thread-safety should be considered high priority to be addressed for M3. Since they are easy to resolve, it should not be a problem to address them until then. All other points that are rather related to the risk of wrong usage of provider methods than to currently relevant issues may be placed in the backlog with lower priority to potentially be addressed after M3.

**Comment by fedejeanne** [comment]
> the first question to answer here is whether `SWTFontRegistry` _needs to be_ thread-safe at all

I went through all calls that reach the method `org.eclipse.swt.internal.SWTFontProvider.getFontRegistry(Device)` and therefore `fontRegistries.computeIfAbsent(device, SWTFontProvider::newFontRegistry)` and I found no need to make the implementations of `SWTFontRegistry` thread-safe for `Display` and only 1 case where it needs to be thread-safe for `Printer`.

## For `Display`: no need to make it thread-safe

Since the only way to break the map via its call to `computeIfAbsent` is if 2 threads call with the same `Display`, but the map is filled early, during the creation of the display (the key). 
Here's the code I used to prove this:

![Image](https://github.com/user-attachments/assets/c646bb51-0986-44ab-8158-062811625026)

Here's the stack trace:

```java
main created an instance of org.eclipse.swt.internal.ScalingSWTFontRegistry
java.lang.RuntimeException
	at org.eclipse.swt.internal.ScalingSWTFontRegistry.<init>(ScalingSWTFontRegistry.java:77)
	at org.eclipse.swt.internal.SWTFontProvider.newFontRegistry(SWTFontProvider.java:53)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.eclipse.swt.internal.SWTFontProvider.getFontRegistry(SWTFontProvider.java:33)
	at org.eclipse.swt.internal.SWTFontProvider.getSystemFont(SWTFontProvider.java:37)
	at org.eclipse.swt.widgets.Display.getSystemFont(Display.java:2506)
	at org.eclipse.swt.widgets.Display.getSystemFont(Display.java:2501)
	at org.eclipse.swt.graphics.Device.init(Device.java:727)
	at org.eclipse.swt.widgets.Display.init(Display.java:2780)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:131)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:597)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:588)
	at org.eclipse.swt.snippets.RaceConditionComputeIfAbsent.main(RaceConditionComputeIfAbsent.java:19)
```

## For `Printer`: it breaks when setting the font

Use this snippet:

```java
public class RaceConditionComputeIfAbsent {
	private static final int NUM_THREADS = 320;
	private static final CyclicBarrier startBarrier = new CyclicBarrier(NUM_THREADS + 1);
	private static final CountDownLatch finishLatch = new CountDownLatch(NUM_THREADS);

	public static void main(String[] args) {
		ExecutorService executorService = Executors.newFixedThreadPool(NUM_THREADS);

		Display display = new Display();
		FontData data = display.getSystemFont().getFontData()[0];
		Font font = new Font(display, data.getName(), 96, SWT.BOLD | SWT.ITALIC);
		Printer printer = new Printer(null);
		GC gc = new GC(printer, 105);

		for (int i = 0; i < NUM_THREADS; i++) {
			executorService.submit(() -> {
				try {
					startBarrier.await();

					try {
						// This call will break the map
						gc.setFont(font);
					} catch (RuntimeException e) {
						e.printStackTrace();
					}

				} catch (InterruptedException | BrokenBarrierException e) {
					e.printStackTrace();
				} finally {
					finishLatch.countDown();
				}
			});
		}

		try {
			startBarrier.await(); // Wait for all threads to reach the barrier
			finishLatch.await(); // Wait until all threads have finished executing
		} catch (InterruptedException | BrokenBarrierException e) {
			e.printStackTrace();
		}

		executorService.shutdown();
	}
}
```

And you'll see lots of:

```java
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at org.eclipse.swt.internal.SWTFontProvider.getFontRegistry(SWTFontProvider.java:32)
	at org.eclipse.swt.internal.SWTFontProvider.getFont(SWTFontProvider.java:40)
	at org.eclipse.swt.graphics.GC.setFont(GC.java:4430)
	at org.eclipse.swt.snippets.RaceConditionComputeIfAbsent.lambda$0(RaceConditionComputeIfAbsent.java:31)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

The solution: using a `ConcurrentHashMap`

**Comment by fedejeanne** [comment]
I created the issues. The only thing I didn't look more in detail is what was mentioned yesterday about possible issues when using a map and having collisions with the `hashCode`. @HeikoKlare could you please give me an example about what you mean by that? I think this is not a problem when using a `ConcurrentHashMap` (my preferred solution) but I want to make sure I understood the problem right.

What I understood was (paraphrasing): _even if the `hashCode` is different for 2 keys, they might land on the same part of the memory because a map might "translate" the hashcode to the same memory address._

Did I get it right?

**Comment by HeikoKlare** [comment]
> What I understood was (paraphrasing): _even if the `hashCode` is different for 2 keys, they might land on the same part of the memory because a map might "translate" the hashcode to the same memory address._

I don't think the details really matter, as HashMap is not thread-safe and we are in a scenario with risks of race conditions upon access. Thus, the implementation details for a potential race condition do not matter (as we cannot rely on implementation detalis anyway), we just need to use a thread-safe data structure. So using ConcurrentHashMap (if it does not have performance drawbacks) sounds fine for me. Otherwise, making only the map modification thread-safe might be a solution.

> For Display: no need to make it thread-safe

As we have discussed, this is not correct. There is a risk for race conditions due to concurrent access, so it _must_ be thread-safe.

**Comment by HeikoKlare** [comment]
We also discussed documenting the non-thread-safety of other operations in SWTFontRegistry, for which we should add an issue.
For other issues, I am not even sure whether we should address them at all, but we might discuss that in the according issues. Would be nice to have self-contained issues instead of just having placeholder issues referencing to a comment in this one, and then close this one instead (as done by the analysis being completed).

**Comment by fedejeanne** [comment]
I Added the missing tags (_SWT_ and _HiDPI_) to all 3 issues, I pasted the current state of the analysis into them (taken from https://github.com/vi-eclipse/Eclipse-Platform/issues/98#issuecomment-2609936211 and https://github.com/vi-eclipse/Eclipse-Platform/issues/98#issuecomment-2624166087) and set their status accordingly.
